SELECT
    C.CAR_ID,
    C.CAR_TYPE,
    ROUND((C.DAILY_FEE * (100 - D.DISCOUNT_RATE) / 100) * 30, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
    ON C.CAR_TYPE = D.CAR_TYPE
WHERE (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV')
  AND D.DURATION_TYPE = '30일 이상'
  -- 대여 가능 조건: 11월 대여 이력과 겹치지 않는 차만 선택
  AND C.CAR_ID NOT IN (
        SELECT H.CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        WHERE H.START_DATE <= '2022-11-30'
          AND H.END_DATE >= '2022-11-01'
  )
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;